version: "3.7"
services:
  Kaddem:
    container_name: Kaddem-s
    build: ../5TWIN6-G1-KADDEM-DevOps
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3307/kaddemApp?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: azizbenismail/kaddem:1.0.9
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
networks:
  springapimysql-net:

volumes:
  db: