version: "2"
services:
  spring:
    depends_on: [mysql]
    image: benismail/kaddem:2-6
    restart: unless-stopped
    ports:
      - "8085:8085"
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: kaddemApp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"