version: "3.9"
services:

  Item:
    container_name: Kaddem-s
    build: .\Kaddem
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kaddemApp?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: "kaddem"
    depends_on:
      - db-mysql

  db-mysql:
      image: "mysql:5.6"
      container_name: db-mysql  
      environment:
        - MYSQL_ROOT_PASSWORD=root
        #- MYSQL_DATABASE=job
      ports:
        - "3306:3306"
      restart: unless-stopped  



