version: "2"
services:
  spring:
    depends_on: [mysql]
    image: azizbenismail/kaddem:3.5
    restart: unless-stopped
    ports:
      - "8085:8085"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: kaddemApp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

